### PR TITLE
WIP - add typings for typescript

### PR DESCRIPTION
**Pull request by evanshortiss**
Addresses #19. These could also be uploaded to DefinitelyTyped if you'd rather not ship them with the module.

CC @bhagyas

### CODE REVIEW

**Comment by evanshortiss** [comment]
TODO: Need to do some more testing, but seems good so far in my local project.

**Comment by jhuckaby** [comment]
I must apologize to you again, but I have never used TypeScript in my entire life, so I don't know what these files do, or more importantly, how to update them in the future.  I cannot take responsibility for maintaining them, so I really cannot merge this PR into the main repo.  It just wouldn't make sense for a non-TypeScript, plain JavaScript project, maintained by a non-TypeScript developer.

I am sorry, and I much appreciate your help and contributions to the project.  Please, by all means, feel free to fork it and host your own TypeScript version, or use the DefinitelyTyped thing you mentioned above (sorry, I don't know what that is either).

Deepest apologies :(

**Comment by evanshortiss** [comment]
Thanks for the response. It's not significantly more effort to add to DefinitelyTyped! 

Not an issue just means they might fall out of sync for a little bit if any major changes occur, but that's easily PR'd to DefinitelyTyped.

**Comment by mmajcica** [comment]
I do like your lib and I would be very happy to see this on DefinitelyTyped. Any updates on this as I can't find it on DefinitelyTyped?

Thanks

**Comment by evanshortiss** [comment]
@mmajcica opened a PR - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37683/files

**Pull request closed without merging**
