### PR TITLE
Update xml.js

### PR DESCRIPTION
**Pull request by 0xff00ff**
i have object with length property (movies list), and lib thinks that it`s an array and crashes with error [TypeError: branch[nodeName].push is not a function]

### CODE REVIEW

**Comment by jhuckaby** [comment]
Thank you for finding this bug.  However, I don't think your patch will work in all cases.  Arrays have a typeof "object" just like plain objects do.  So your modified `isa_hash()` will return true for arrays.

``` js
> typeof []
'object'
```

I'll look around and try to find a better way to do this.  I've seen a bunch of methods, but they're all crazy complex.

**Comment by jhuckaby** [comment]
Looks like this is the preferred way:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

I'll work on using this.

**Comment by 0xff00ff** [comment]
yes, this way is much better. but you should not check length on object, this property can be.

var isa_hash = exports.isaHash = function isa_hash(arg) {

```
// determine if arg is a hash

return( !!arg && (typeof(arg) == 'object') && (arg !== null) && !isa_array(arg) );

};
```

something like this, to exclude array, but and accept objects 'like' array

**Comment by jhuckaby** [comment]
Fixed in https://github.com/jhuckaby/pixl-xml/commit/44c0b50e2a1e1296ff92f6b26368e8be62c8ace5.

Tagged [v1.0.5](https://github.com/jhuckaby/pixl-xml/releases/tag/v1.0.5).

**Comment by 0xff00ff** [comment]
great, thanks.

**Pull request closed without merging**
