### PR TITLE
make sorting optional when creating xml

### PR DESCRIPTION
**Pull request by orangewise**
I used your module to create xsl files. In xsl the order of elements can make a difference, that's why I added an extra parameter to skip sorting and hope for the best (knowing that order is not quaranteed ;)

### CODE REVIEW

**Comment by jhuckaby** [comment]
Thank you @orangewise!  This looks good, but unfortunately your text editor has ripped apart all my whitespace.  Check out the diff to see.  Is there any way to change your PR to only change the code you actually changed, and not remove all my whitespace?

Thanks!

**Comment by orangewise** [comment]
Hi @jhuckaby, i tried to do this but it I could not get it right...  Feel free to ignore this PR :)

**Comment by jhuckaby** [comment]
No worries!  I'll try to incorporate your change in the next version anyway.  I can just manually copy / paste the code.  Thanks again!

**Comment by jhuckaby** [comment]
Included in [v1.0.11](https://github.com/jhuckaby/pixl-xml/releases/tag/v1.0.11).  Thanks again!

**Pull request closed without merging**
